version: '3'

services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"